apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    app: runningrecords
    component: redis-server
    type: single
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  #type: NodePort
  selector:
    app: runningrecords
    component: redis-server
    type: single