apiVersion: v1
kind: Service
metadata:
  name: webservice
  labels:
    app: runningrecords
    component: webservice
spec:
  type: NodePort
  selector:
    app: runningrecords
    component: webservice
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31110