---
- name: misc task on Centos/7 instance
  hosts: "*"
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - debug: var=app_server
    
- name: deploy
  hosts: app_server
  become: true
  vars:
    redis_port: 6379
    redis_databases: 1
    node_version: 6.1.0
    repo_path: /vagrant/runningrecords

  roles:
  - role: redis/install
    tags: install
  - role: nodejs/install
    tags: install
  - role: nodejs-app/install
    tags: install
  - role: nodejs-app/healthchecks
    tags: check
    

