--- 
- name: Install packages based on package.json using the npm
  become: true
  npm:
    path: "{{ repo_path }}"
    state: present

- name: Run app
  become: true
  command: npm start
  args:
    chdir: "{{ repo_path }}"