# data volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  labels:
    app: runningrecords
    component: redis-server
    type: single
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi