---
- name: Install EPEL repo
  yum:
    name: epel-release
    state: present
    
- name: Ensure Redis is present
  yum: pkg=redis state=latest
  become: true

- name: Ensure Redis is started
  service: name=redis state=started enabled=yes
  become: true

- name: Redis Restart
  service: name=redis state=restarted enabled=yes
  become: true
