name: Deploy

on:
  workflow_run:
    workflows: [Node.js CI]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with: 
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "runningrecords"
          heroku_email: "nathalie.descusse@gmail.com"
          appdir: userapi

